var classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_entity_selector_argument =
[
    [ "ManyEntities", "classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_entity_selector_argument_1_1_many_entities.html", "classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_entity_selector_argument_1_1_many_entities" ],
    [ "ManyPlayers", "classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_entity_selector_argument_1_1_many_players.html", "classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_entity_selector_argument_1_1_many_players" ],
    [ "OneEntity", "classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_entity_selector_argument_1_1_one_entity.html", "classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_entity_selector_argument_1_1_one_entity" ],
    [ "OnePlayer", "classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_entity_selector_argument_1_1_one_player.html", "classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_entity_selector_argument_1_1_one_player" ]
];