package io.github.jorelali.commandapi.api.arguments;

public enum CommandAPIArgumentType {

	ADVANCEMENT, AXIS, CHAT, CHAT_COMPONENT, CHATCOLOR, CUSTOM, ENCHANTMENT, 
	ENTITY_SELECTOR, ENTITY_TYPE, ENVIRONMENT, FLOAT_RANGE, FUNCTION, INT_RANGE, 
	ITEM_SLOT, ITEMSTACK, LITERAL, LOCATION, LOCATION_2D, LOOT_TABLE, OBJECTIVE, 
	OBJECTIVE_CRITERIA, PARTICLE, PLAYER, POTION_EFFECT, RECIPE, ROTATION, 
	SCOREBOARD_SLOT, SIMPLE_TYPE, SOUND, TEAM, TIME, SCORE_HOLDER, NBT_COMPOUND, MATH_OPERATION, SUPER_LITERAL

}
