package io.github.jorelali.commandapi.api.arguments;

public enum CommandAPIArgumentType {

	CUSTOM, ENCHANTMENT, ENTITY_SELECTOR, ENTITY_TYPE, SIMPLE_TYPE, LITERAL, CHATCOLOR, CHAT_COMPONENT, FUNCTION, ITEMSTACK, LOCATION, LOOT_TABLE, PARTICLE, PLAYER, POTION_EFFECT

}
