var searchData=
[
  ['aadvancementargument_0',['AAdvancementArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_advancement_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aadventurechatargument_1',['AAdventureChatArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_adventure_chat_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aadventurechatcomponentargument_2',['AAdventureChatComponentArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_adventure_chat_component_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aangleargument_3',['AAngleArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_angle_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aaxisargument_4',['AAxisArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_axis_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['abiomeargument_5',['ABiomeArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_biome_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['ablockpredicateargument_6',['ABlockPredicateArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_block_predicate_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['ablockstateargument_7',['ABlockStateArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_block_state_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['abooleanargument_8',['ABooleanArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_boolean_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['abstractargument_9',['AbstractArgument',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_abstract_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['abstractargument_3c_20t_2c_20argument_3c_20t_20_3e_2c_20argument_3c_3f_3e_2c_20commandsender_20_3e_10',['AbstractArgument&lt; T, Argument&lt; T &gt;, Argument&lt;?&gt;, CommandSender &gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_abstract_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['abstractargumenttree_11',['AbstractArgumentTree',['../classdev_1_1jorel_1_1commandapi_1_1_abstract_argument_tree.html',1,'dev::jorel::commandapi']]],
  ['abstractblockcommandsender_12',['AbstractBlockCommandSender',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_block_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractblockcommandsender_3c_20blockcommandsender_20_3e_13',['AbstractBlockCommandSender&lt; BlockCommandSender &gt;',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_block_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractcommandapicommand_14',['AbstractCommandAPICommand',['../classdev_1_1jorel_1_1commandapi_1_1_abstract_command_a_p_i_command.html',1,'dev::jorel::commandapi']]],
  ['abstractcommandapicommand_3c_20commandapicommand_2c_20argument_3c_3f_3e_2c_20commandsender_20_3e_15',['AbstractCommandAPICommand&lt; CommandAPICommand, Argument&lt;?&gt;, CommandSender &gt;',['../classdev_1_1jorel_1_1commandapi_1_1_abstract_command_a_p_i_command.html',1,'dev::jorel::commandapi']]],
  ['abstractcommandsender_16',['AbstractCommandSender',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractcommandtree_17',['AbstractCommandTree',['../classdev_1_1jorel_1_1commandapi_1_1_abstract_command_tree.html',1,'dev::jorel::commandapi']]],
  ['abstractcommandtree_3c_20commandtree_2c_20argument_3c_3f_3e_2c_20commandsender_20_3e_18',['AbstractCommandTree&lt; CommandTree, Argument&lt;?&gt;, CommandSender &gt;',['../classdev_1_1jorel_1_1commandapi_1_1_abstract_command_tree.html',1,'dev::jorel::commandapi']]],
  ['abstractconsolecommandsender_19',['AbstractConsoleCommandSender',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_console_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractconsolecommandsender_3c_20consolecommandsender_20_3e_20',['AbstractConsoleCommandSender&lt; ConsoleCommandSender &gt;',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_console_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractentity_21',['AbstractEntity',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_entity.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractentity_3c_20entity_20_3e_22',['AbstractEntity&lt; Entity &gt;',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_entity.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractfeedbackforwardingcommandsender_23',['AbstractFeedbackForwardingCommandSender',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_feedback_forwarding_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractfeedbackforwardingcommandsender_3c_20feedbackforwardingsender_20_3e_24',['AbstractFeedbackForwardingCommandSender&lt; FeedbackForwardingSender &gt;',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_feedback_forwarding_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractnativeproxycommandsender_25',['AbstractNativeProxyCommandSender',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_native_proxy_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractnativeproxycommandsender_3c_20nativeproxycommandsender_20_3e_26',['AbstractNativeProxyCommandSender&lt; NativeProxyCommandSender &gt;',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_native_proxy_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractplayer_27',['AbstractPlayer',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_player.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractplayer_3c_20player_20_3e_28',['AbstractPlayer&lt; Player &gt;',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_player.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractproxiedcommandsender_29',['AbstractProxiedCommandSender',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_proxied_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractproxiedcommandsender_3c_20proxiedcommandsender_20_3e_30',['AbstractProxiedCommandSender&lt; ProxiedCommandSender &gt;',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_proxied_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractremoteconsolecommandsender_31',['AbstractRemoteConsoleCommandSender',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_remote_console_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['abstractremoteconsolecommandsender_3c_20remoteconsolecommandsender_20_3e_32',['AbstractRemoteConsoleCommandSender&lt; RemoteConsoleCommandSender &gt;',['../interfacedev_1_1jorel_1_1commandapi_1_1commandsenders_1_1_abstract_remote_console_command_sender.html',1,'dev::jorel::commandapi::commandsenders']]],
  ['achatargument_33',['AChatArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_chat_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['achatcolorargument_34',['AChatColorArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_chat_color_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['achatcomponentargument_35',['AChatComponentArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_chat_component_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['adoubleargument_36',['ADoubleArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_double_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['advancementargument_37',['AdvancementArgument',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_advancement_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['adventurechatargument_38',['AdventureChatArgument',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_adventure_chat_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['adventurechatcolorargument_39',['AdventureChatColorArgument',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_adventure_chat_color_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['adventurechatcomponentargument_40',['AdventureChatComponentArgument',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_adventure_chat_component_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['aenchantmentargument_41',['AEnchantmentArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_enchantment_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aentityselectorargument_42',['AEntitySelectorArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_entity_selector_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aentitytypeargument_43',['AEntityTypeArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_entity_type_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['afloatargument_44',['AFloatArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_float_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['afloatrangeargument_45',['AFloatRangeArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_float_range_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['afunctionargument_46',['AFunctionArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_function_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['agreedystringargument_47',['AGreedyStringArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_greedy_string_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aintegerargument_48',['AIntegerArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_integer_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aintegerrangeargument_49',['AIntegerRangeArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_integer_range_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aitemstackargument_50',['AItemStackArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_item_stack_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aitemstackpredicateargument_51',['AItemStackPredicateArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_item_stack_predicate_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['alias_52',['Alias',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1_alias.html',1,'dev::jorel::commandapi::annotations']]],
  ['aliteralargument_53',['ALiteralArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_literal_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['alocation2dargument_54',['ALocation2DArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_location2_d_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['alocationargument_55',['ALocationArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_location_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['alongargument_56',['ALongArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_long_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aloottableargument_57',['ALootTableArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_loot_table_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['amathoperationargument_58',['AMathOperationArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_math_operation_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['ambiguityconsumer_59',['AmbiguityConsumer',['../interfacecom_1_1mojang_1_1brigadier_1_1_ambiguity_consumer.html',1,'com::mojang::brigadier']]],
  ['amultiliteralargument_60',['AMultiLiteralArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_multi_literal_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['anamespacedkeyargument_61',['ANamespacedKeyArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_namespaced_key_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['anbtcompoundargument_62',['ANBTCompoundArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_n_b_t_compound_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['angleargument_63',['AngleArgument',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_angle_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['annotations_64',['Annotations',['../classdev_1_1jorel_1_1commandapi_1_1annotations_1_1_annotations.html',1,'dev::jorel::commandapi::annotations']]],
  ['aobjectiveargument_65',['AObjectiveArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_objective_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aobjectivecriteriaargument_66',['AObjectiveCriteriaArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_objective_criteria_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aofflineplayerargument_67',['AOfflinePlayerArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_offline_player_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aparticleargument_68',['AParticleArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_particle_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aplayerargument_69',['APlayerArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_player_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['apotioneffectargument_70',['APotionEffectArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_potion_effect_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['arecipeargument_71',['ARecipeArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_recipe_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['argument_72',['Argument',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argument_3c_20b_20_3e_73',['Argument&lt; B &gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argument_3c_20basecomponent_5b_5d_3e_74',['Argument&lt; BaseComponent[]&gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argument_3c_20blockdata_20_3e_75',['Argument&lt; BlockData &gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argument_3c_20collection_20_3e_76',['Argument&lt; Collection &gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argument_3c_20commandresult_20_3e_77',['Argument&lt; CommandResult &gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argument_3c_20component_20_3e_78',['Argument&lt; Component &gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argument_3c_20entity_20_3e_79',['Argument&lt; Entity &gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argument_3c_20linkedhashmap_20_3e_80',['Argument&lt; LinkedHashMap &gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argument_3c_20list_20_3e_81',['Argument&lt; List &gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argument_3c_20player_20_3e_82',['Argument&lt; Player &gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argument_3c_20predicate_20_3e_83',['Argument&lt; Predicate &gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argument_3c_20string_20_3e_84',['Argument&lt; String &gt;',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument.html',1,'dev::jorel::commandapi::arguments']]],
  ['argumentbuilder_85',['ArgumentBuilder',['../classcom_1_1mojang_1_1brigadier_1_1builder_1_1_argument_builder.html',1,'com::mojang::brigadier::builder']]],
  ['argumentbuilder_3c_20s_2c_20literalargumentbuilder_3c_20s_20_3e_20_3e_86',['ArgumentBuilder&lt; S, LiteralArgumentBuilder&lt; S &gt; &gt;',['../classcom_1_1mojang_1_1brigadier_1_1builder_1_1_argument_builder.html',1,'com::mojang::brigadier::builder']]],
  ['argumentbuilder_3c_20s_2c_20requiredargumentbuilder_3c_20s_2c_20t_20_3e_20_3e_87',['ArgumentBuilder&lt; S, RequiredArgumentBuilder&lt; S, T &gt; &gt;',['../classcom_1_1mojang_1_1brigadier_1_1builder_1_1_argument_builder.html',1,'com::mojang::brigadier::builder']]],
  ['argumentcommandnode_88',['ArgumentCommandNode',['../classcom_1_1mojang_1_1brigadier_1_1tree_1_1_argument_command_node.html',1,'com::mojang::brigadier::tree']]],
  ['argumentsubtype_89',['ArgumentSubType',['../enumdev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument_sub_type.html',1,'dev::jorel::commandapi::arguments']]],
  ['argumentsuggestions_90',['ArgumentSuggestions',['../interfacedev_1_1jorel_1_1commandapi_1_1arguments_1_1_argument_suggestions.html',1,'dev::jorel::commandapi::arguments']]],
  ['argumenttype_91',['ArgumentType',['../interfacecom_1_1mojang_1_1brigadier_1_1arguments_1_1_argument_type.html',1,'com::mojang::brigadier::arguments']]],
  ['argumenttype_3c_20boolean_20_3e_92',['ArgumentType&lt; Boolean &gt;',['../interfacecom_1_1mojang_1_1brigadier_1_1arguments_1_1_argument_type.html',1,'com::mojang::brigadier::arguments']]],
  ['argumenttype_3c_20double_20_3e_93',['ArgumentType&lt; Double &gt;',['../interfacecom_1_1mojang_1_1brigadier_1_1arguments_1_1_argument_type.html',1,'com::mojang::brigadier::arguments']]],
  ['argumenttype_3c_20float_20_3e_94',['ArgumentType&lt; Float &gt;',['../interfacecom_1_1mojang_1_1brigadier_1_1arguments_1_1_argument_type.html',1,'com::mojang::brigadier::arguments']]],
  ['argumenttype_3c_20integer_20_3e_95',['ArgumentType&lt; Integer &gt;',['../interfacecom_1_1mojang_1_1brigadier_1_1arguments_1_1_argument_type.html',1,'com::mojang::brigadier::arguments']]],
  ['argumenttype_3c_20long_20_3e_96',['ArgumentType&lt; Long &gt;',['../interfacecom_1_1mojang_1_1brigadier_1_1arguments_1_1_argument_type.html',1,'com::mojang::brigadier::arguments']]],
  ['argumenttype_3c_20string_20_3e_97',['ArgumentType&lt; String &gt;',['../interfacecom_1_1mojang_1_1brigadier_1_1arguments_1_1_argument_type.html',1,'com::mojang::brigadier::arguments']]],
  ['argumenttype_3c_3f_3e_98',['ArgumentType&lt;?&gt;',['../interfacecom_1_1mojang_1_1brigadier_1_1arguments_1_1_argument_type.html',1,'com::mojang::brigadier::arguments']]],
  ['arotationargument_99',['ARotationArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_rotation_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['ascoreboardslotargument_100',['AScoreboardSlotArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_scoreboard_slot_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['ascoreholderargument_101',['AScoreHolderArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_score_holder_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['asoundargument_102',['ASoundArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_sound_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['astringargument_103',['AStringArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_string_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['ateamargument_104',['ATeamArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_team_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['atextargument_105',['ATextArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_text_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['atimeargument_106',['ATimeArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_time_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['auuidargument_107',['AUUIDArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_u_u_i_d_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['aworldargument_108',['AWorldArgument',['../interfacedev_1_1jorel_1_1commandapi_1_1annotations_1_1arguments_1_1_a_world_argument.html',1,'dev::jorel::commandapi::annotations::arguments']]],
  ['axisargument_109',['AxisArgument',['../classdev_1_1jorel_1_1commandapi_1_1arguments_1_1_axis_argument.html',1,'dev::jorel::commandapi::arguments']]]
];
