package dev.jorel.commandapi.ktannotations

import dev.jorel.commandapi.annotations.arguments.*
import dev.jorel.commandapi.arguments.PlayerArgument

val argumentAnnotations = arrayOf(
	AAdvancementArgument::class,
	AAdventureChatArgument::class,
	AAdventureChatComponentArgument::class,
	AAngleArgument::class,
	AAxisArgument::class,
	ABiomeArgument::class,
	ABlockPredicateArgument::class,
	ABlockStateArgument::class,
	ABooleanArgument::class,
	AChatArgument::class,
	AChatColorArgument::class,
	AChatComponentArgument::class,
	ADoubleArgument::class,
	AEnchantmentArgument::class,
	AEntitySelectorArgument::class,
	AEntityType::class,
	AEnvironmentArgument::class,
	AFloatArgument::class,
	AFloatRangeArgument::class,
	AFunctionArgument::class,
	AGreedyStringArgument::class,
	AIntegerArgument::class,
	AIntegerRangeArgument::class,
	AItemStackArgument::class,
	AItemStackPredicateArgument::class,
	ALiteralArgument::class,
	ALocation2DArgument::class,
	ALocationArgument::class,
	ALongArgument::class,
	ALootTableArgument::class,
	AMathOperationArgument::class,
	AMultiLiteralArgument::class,
	ANBTCompoundArgument::class,
	AObjectiveArgument::class,
	AObjectiveCriteriaArgument::class,
	AOfflinePlayerArgument::class,
	AParticleArgument::class,
	APlayerArgument::class,
	APotionEffectArgument::class,
	ARecipeArgument::class,
	ARotationArgument::class,
	AScoreboardSlotArgument::class,
	AScoreHolderArgument::class,
	ASoundArgument::class,
	AStringArgument::class,
	ATeamArgument::class,
	ATextArgument::class,
	ATimeArgument::class,
	AUUIDArgument::class
)

val argumentsPackage: String = PlayerArgument::class.java.packageName